name: .NET

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env: 
      # Test account API key
       CAPI_KEY: "M2Q4OGJkYWYtMGI3NC00MjA0LWE4NzItMzZiYmNlZjkxMjc4"
      run: dotnet test --no-build --verbosity normal
